require File.expand_path('shop/lib/midia.rb')
require File.expand_path('shop/lib/dvd.rb')
require File.expand_path('shop/lib/cd.rb')
require File.expand_path('shop/lib/livro.rb')
require File.expand_path('shop/lib/biblioteca.rb')
require File.expand_path('shop/lib/relatorio.rb')
require File.expand_path('shop/lib/banco_de_arquivos.rb')